apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sim-prov

resources:
  - ../../base

commonLabels:
  environment: prod

commonAnnotations:
  sim-prov.io/owner: sayuj@itm-skills.edu.in
  sim-prov.io/runbook: https://sim-prov.example.com/runbooks

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: api
  - path: replicas-patch-worker.yaml
    target:
      kind: Deployment
      name: worker
  - path: ingress-host-patch.yaml
    target:
      kind: Ingress
      name: sim-prov

images:
  - name: sim-prov/api
    newName: ghcr.io/itm-skills/sim-prov/api
    newTag: latest
  - name: sim-prov/worker
    newName: ghcr.io/itm-skills/sim-prov/worker
    newTag: latest
  - name: sim-prov/mock-hlr
    newName: ghcr.io/itm-skills/sim-prov/mock-hlr
    newTag: latest
  - name: sim-prov/frontend
    newName: ghcr.io/itm-skills/sim-prov/frontend
    newTag: latest
