name: sim-prov-elk

networks:
  provisioning-net:
    external: true
    name: provisioning-net

volumes:
  elasticsearch-data:
    external: true
    name: sim-prov_elasticsearch-data

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: sim-prov-elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      bootstrap.memory_lock: "true"
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ../elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports: ["9200:9200"]
    networks: [provisioning-net]

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: sim-prov-logstash
    depends_on: [elasticsearch]
    environment:
      LS_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - ../logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "9600:9600"
    networks: [provisioning-net]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: sim-prov-kibana
    depends_on: [elasticsearch]
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - ../kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports: ["5601:5601"]
    networks: [provisioning-net]

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.4
    container_name: sim-prov-filebeat
    user: root
    depends_on: [logstash]
    command: ["-strict.perms=false", "-e"]
    volumes:
      - ../filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [provisioning-net]
