apiVersion: v1
kind: ServiceAccount
metadata:
  name: sim-prov-api
  namespace: sim-prov
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/sim-prov-api-irsa
    vault.hashicorp.com/role: sim-prov-api
  labels:
    app.kubernetes.io/name: sim-prov
    app.kubernetes.io/component: api
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sim-prov-worker
  namespace: sim-prov
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/sim-prov-worker-irsa
    vault.hashicorp.com/role: sim-prov-worker
  labels:
    app.kubernetes.io/name: sim-prov
    app.kubernetes.io/component: worker
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sim-prov-mock-hlr
  namespace: sim-prov
  labels:
    app.kubernetes.io/name: sim-prov
    app.kubernetes.io/component: mock-hlr
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sim-prov-frontend
  namespace: sim-prov
  labels:
    app.kubernetes.io/name: sim-prov
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
